const assert = require('node:assert/strict');
const fs = require('node:fs');
const catalog = require('../assets/exercise-visual-catalog.js');
const source = fs.readFileSync('vdsen-coach.html', 'utf8');
const block = source.match(/const BASE_EXERCISES = \[(.*?)\];\s*\n\s*document\.getElementById\("loadBaseBtn"\)/s)[1];
const names = [...block.matchAll(/name:"([^"]+)"/g)].map(x => x[1]);
const visual = catalog.gyms['smart-fit-san-diego'];
const norm = x => String(x).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();
const exact = new Set(visual.entries.flatMap(e => [e.exerciseName, ...(e.aliases || [])]).map(norm));
const legacy = new Set(visual.legacyEntries.map(e => e.exerciseName).map(norm));
const mapped = names.filter(n => exact.has(norm(n)));
const added = names.filter(n => legacy.has(norm(n)));
assert.equal(names.length, 85);
assert.equal(mapped.length, 0);
assert.equal(added.length, visual.legacyEntries.length);
assert.equal(visual.legacyEntries.length, 8);
assert.equal(new Set(visual.legacyEntries.map(e => e.exerciseId)).size, 8);
assert.ok(visual.legacyEntries.every(e => e.assetRef && e.setup && e.execution && e.technicalObjective && e.commonErrors.length));
assert.match(fs.readFileSync('vdsen-cliente.html', 'utf8'), /legacyEntries/);
console.log('T460 — explicit legacy Coach exercise visual coverage: PASS');
